apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/app
                  operator: In
                  values:
                  - "$(elasticsearch-data-statefulset-app-label)"
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - "$(elasticsearch-data-statefulset-instance-label)"
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                  - "$(elasticsearch-data-statefulset-component-label)"
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 180
      volumes:
        - emptyDir:
            medium: ""
          name: "storage"