---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    tier: logging-plane
spec:
  serviceName: elasticsearch
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: logging-plane
  template:
    metadata:
      labels:
        tier: logging-plane
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      priorityClassName: infra
      containers:
      - name: elasticsearch
        image: mintel/elasticsearch:v6.6.0-1
        env:
          - name: CLUSTER_NAME
            value: logs
          - name: DISCOVERY_SERVICE
            value: "$(elasticsearch-service-name).monitoring.svc.cluster.local"
          - name: HTTP_ENABLE
            value: "true"
          - name: MINIMUM_NUMBER_OF_MASTERS
            value: "2"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NETWORK_ADDRESS_CACHE_NEGATIVE_TTL
            value: "2"
          - name: NETWORK_ADDRESS_CACHE_TTL
            value: "2"
          - name: NETWORK_HOST
            value: "0.0.0.0"
          # PROCESSORS NEED TO BE AN INTEGER - SET LIMITS CPU ACCORDINGLY
          - name: PROCESSORS
            valueFrom:
              resourceFieldRef:
                resource: limits.cpu
        resources:
          requests:
            cpu: 0.25
          limits:
            cpu: 2
        ports:
        - containerPort: 9200
          name: http
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        livenessProbe:
          tcpSocket:
            port: transport
          initialDelaySeconds: 40
          periodSeconds: 10
        volumeMounts:
        - name: storage
          mountPath: /data
