---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

commonLabels:
  app.kubernetes.io/part-of: elasticstack
  app.kubernetes.io/managed-by: kustomize
  part-of: elasticstack
  managed-by: kustomize

bases:
  - ./elasticsearch-curator
  - ./elasticsearch-data
  - ./elasticsearch-master
  - ./kibana

resources:
  - ./networkPolicy.yml

# TODO: Following in Kibana needs either patch or vars to set
# - --redirection-url=https://kibana.svc.gke1.k8s-dev.mintel.com
# - --discovery-url=https://dex.svc.gke1.k8s-dev.mintel.com/.well-known/openid-configuration